services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  backend:
    build:
      context: ./backend-app
      dockerfile: Dockerfile.prod
      target: production
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - NGINX_PORT=${NGINX_PORT:-8080}
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "${NGINX_PORT:-8080}:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
