name: Horas tests

on:
  push:
    branches:
      - main
      - dev
      - devback
      - back-tests

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
        working-directory: ./backend-app
      - name: Run tests
        run: npm test
        working-directory: ./backend-app
